import type { Category } from '@/types'

export const SKILLS_BY_CATEGORY: Record<Category, string[]> = {
  dancer: [
    'Bollywood',
    'Kathak',
    'Classical Indian dance',
    'Ballet',
    'Contemporary',
    'Hip-hop',
    'Street dance',
    'Breakdancing',
    'Latin',
    'Salsa',
    'Bachata',
    'Ballroom',
    'Jazz',
    'Tap',
    'Flamenco',
    'Afrobeats',
    'Belly dance',
    'K-pop',
    'Irish dance',
    'Aerial dance',
    'Popping & locking',
    'Waacking',
    'Voguing',
    'Dancehall',
    'Physical theatre',
    'Musical theatre dance',
    'Bhangra',
    'Folk dance',
  ],
  actor: [
    'Film acting',
    'Theatre acting',
    'Television acting',
    'Improvisation',
    'Stage combat',
    'Boxing',
    'Martial arts',
    'Stunts',
    'Motion capture',
    'Voice acting',
    'Character work',
    'Physical theatre',
    'Musical theatre',
    'Comedy',
    'Method acting',
    'Accent work',
    'Emotional range',
    'Animation voice',
    'Documentary presenting',
    'Immersive theatre',
  ],
  photographer_videographer: [
    'Commercial photography',
    'Portrait photography',
    'Fashion photography',
    'Wedding photography',
    'Event photography',
    'Product photography',
    'Editorial photography',
    'Documentary photography',
    'Commercial videography',
    'Cinematography',
    'Music videos',
    'Events videography',
    'Drone',
    'Aerial',
    'Vlog',
  ],
  content_creator: [
    'Food & beverage content',
    'Food photography',
    'Recipe content',
    'Restaurant reviews',
    'Cocktail & drinks content',
    'Travel content',
    'Lifestyle content',
    'Fashion content',
    'Beauty & makeup',
    'Fitness content',
    'Wellness content',
    'Comedy & entertainment',
    'Educational content',
    'Product reviews',
    'Short-form video',
    'Long-form video',
    'Photography',
    'Copywriting',
    'Brand partnerships',
    'Podcast hosting',
  ],
}


export const CATEGORY_LABELS: Record<Category, string> = {
  dancer: 'Dancer',
  actor: 'Actor / Model',
  photographer_videographer: 'Photographer / Videographer',
  content_creator: 'Content Creator',
}

export const PROFICIENCY_LABELS = {
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
  expert: 'Expert',
}
